### ISSUE TITLE
How to provide private templates?

### ISSUE THREAD

**Issue by max06** [devcontainers/template-starter#27] opened 2023-11-23 21:10 UTC
Hello there!

The documentation says:
> Templates listed here will be presented in the UX of [supporting tools](https://containers.dev/supporting).

Is there a way to provide an additional source for templates to select from, like from a non-public gitlab instance, the same way current templates are shown?

(Alternatively I'm looking for a way to share one container with multiple repositories, something like `Reopen/Clone in existing container`...)

**Comment by samruddhikhandale** [comment] 2023-11-28 00:29
Hello! 👋 

I believe you are looking for a private index for private Templates? I don't think we currently have that wired up, but we had similar discussions in the past. See https://github.com/devcontainers/spec/discussions/136 and https://github.com/devcontainers/spec/issues/71#issuecomment-1415959648.

Do those issues sound similar to your question? If so, feel free to chime in https://github.com/devcontainers/spec/issues/71

**Comment by bamurtaugh** [comment] 2023-11-29 22:00
Thanks again for opening! Going to close this as a dupe of the other links @samruddhikhandale provided, but please let us know if your request is different, and happy to reopen.

**Closed by bamurtaugh** 2023-11-29 22:00 UTC
